// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "config.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace config {

namespace {

const ::google::protobuf::Descriptor* CalendarConfig_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CalendarConfig_reflection_ = NULL;
const ::google::protobuf::Descriptor* MonthDay_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MonthDay_reflection_ = NULL;
const ::google::protobuf::Descriptor* RGB_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RGB_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_config_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_config_2eproto() {
  protobuf_AddDesc_config_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "config.proto");
  GOOGLE_CHECK(file != NULL);
  CalendarConfig_descriptor_ = file->message_type(0);
  static const int CalendarConfig_offsets_[12] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CalendarConfig, num_years_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CalendarConfig, special_day_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CalendarConfig, cell_size_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CalendarConfig, font_size_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CalendarConfig, line_width_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CalendarConfig, rgb_special_day_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CalendarConfig, rgb_sunday_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CalendarConfig, rgb_holiday_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CalendarConfig, rgb_common_day_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CalendarConfig, rgb_line_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CalendarConfig, rgb_number_bright_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CalendarConfig, rgb_number_dark_),
  };
  CalendarConfig_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CalendarConfig_descriptor_,
      CalendarConfig::default_instance_,
      CalendarConfig_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CalendarConfig, _has_bits_[0]),
      -1,
      -1,
      sizeof(CalendarConfig),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CalendarConfig, _internal_metadata_),
      -1);
  MonthDay_descriptor_ = file->message_type(1);
  static const int MonthDay_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MonthDay, month_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MonthDay, day_),
  };
  MonthDay_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MonthDay_descriptor_,
      MonthDay::default_instance_,
      MonthDay_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MonthDay, _has_bits_[0]),
      -1,
      -1,
      sizeof(MonthDay),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MonthDay, _internal_metadata_),
      -1);
  RGB_descriptor_ = file->message_type(2);
  static const int RGB_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RGB, red_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RGB, green_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RGB, blue_),
  };
  RGB_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      RGB_descriptor_,
      RGB::default_instance_,
      RGB_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RGB, _has_bits_[0]),
      -1,
      -1,
      sizeof(RGB),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RGB, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_config_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CalendarConfig_descriptor_, &CalendarConfig::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MonthDay_descriptor_, &MonthDay::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      RGB_descriptor_, &RGB::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_config_2eproto() {
  delete CalendarConfig::default_instance_;
  delete CalendarConfig_reflection_;
  delete MonthDay::default_instance_;
  delete MonthDay_reflection_;
  delete RGB::default_instance_;
  delete RGB_reflection_;
}

void protobuf_AddDesc_config_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_config_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014config.proto\022\006config\"\216\003\n\016CalendarConfi"
    "g\022\025\n\tnum_years\030\001 \001(\005:\00230\022%\n\013special_day\030"
    "\002 \003(\0132\020.config.MonthDay\022\025\n\tcell_size\030\003 \001"
    "(\005:\00230\022\025\n\tfont_size\030\004 \001(\005:\00215\022\025\n\nline_wi"
    "dth\030\005 \001(\005:\0013\022$\n\017rgb_special_day\030\006 \001(\0132\013."
    "config.RGB\022\037\n\nrgb_sunday\030\007 \001(\0132\013.config."
    "RGB\022 \n\013rgb_holiday\030\010 \001(\0132\013.config.RGB\022#\n"
    "\016rgb_common_day\030\t \001(\0132\013.config.RGB\022\035\n\010rg"
    "b_line\030\n \001(\0132\013.config.RGB\022&\n\021rgb_number_"
    "bright\030\013 \001(\0132\013.config.RGB\022$\n\017rgb_number_"
    "dark\030\014 \001(\0132\013.config.RGB\"&\n\010MonthDay\022\r\n\005m"
    "onth\030\001 \002(\005\022\013\n\003day\030\002 \002(\005\"/\n\003RGB\022\013\n\003red\030\001 "
    "\002(\005\022\r\n\005green\030\002 \002(\005\022\014\n\004blue\030\003 \002(\005", 512);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "config.proto", &protobuf_RegisterTypes);
  CalendarConfig::default_instance_ = new CalendarConfig();
  MonthDay::default_instance_ = new MonthDay();
  RGB::default_instance_ = new RGB();
  CalendarConfig::default_instance_->InitAsDefaultInstance();
  MonthDay::default_instance_->InitAsDefaultInstance();
  RGB::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_config_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_config_2eproto {
  StaticDescriptorInitializer_config_2eproto() {
    protobuf_AddDesc_config_2eproto();
  }
} static_descriptor_initializer_config_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CalendarConfig::kNumYearsFieldNumber;
const int CalendarConfig::kSpecialDayFieldNumber;
const int CalendarConfig::kCellSizeFieldNumber;
const int CalendarConfig::kFontSizeFieldNumber;
const int CalendarConfig::kLineWidthFieldNumber;
const int CalendarConfig::kRgbSpecialDayFieldNumber;
const int CalendarConfig::kRgbSundayFieldNumber;
const int CalendarConfig::kRgbHolidayFieldNumber;
const int CalendarConfig::kRgbCommonDayFieldNumber;
const int CalendarConfig::kRgbLineFieldNumber;
const int CalendarConfig::kRgbNumberBrightFieldNumber;
const int CalendarConfig::kRgbNumberDarkFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CalendarConfig::CalendarConfig()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:config.CalendarConfig)
}

void CalendarConfig::InitAsDefaultInstance() {
  rgb_special_day_ = const_cast< ::config::RGB*>(&::config::RGB::default_instance());
  rgb_sunday_ = const_cast< ::config::RGB*>(&::config::RGB::default_instance());
  rgb_holiday_ = const_cast< ::config::RGB*>(&::config::RGB::default_instance());
  rgb_common_day_ = const_cast< ::config::RGB*>(&::config::RGB::default_instance());
  rgb_line_ = const_cast< ::config::RGB*>(&::config::RGB::default_instance());
  rgb_number_bright_ = const_cast< ::config::RGB*>(&::config::RGB::default_instance());
  rgb_number_dark_ = const_cast< ::config::RGB*>(&::config::RGB::default_instance());
}

CalendarConfig::CalendarConfig(const CalendarConfig& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:config.CalendarConfig)
}

void CalendarConfig::SharedCtor() {
  _cached_size_ = 0;
  num_years_ = 30;
  cell_size_ = 30;
  font_size_ = 15;
  line_width_ = 3;
  rgb_special_day_ = NULL;
  rgb_sunday_ = NULL;
  rgb_holiday_ = NULL;
  rgb_common_day_ = NULL;
  rgb_line_ = NULL;
  rgb_number_bright_ = NULL;
  rgb_number_dark_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CalendarConfig::~CalendarConfig() {
  // @@protoc_insertion_point(destructor:config.CalendarConfig)
  SharedDtor();
}

void CalendarConfig::SharedDtor() {
  if (this != default_instance_) {
    delete rgb_special_day_;
    delete rgb_sunday_;
    delete rgb_holiday_;
    delete rgb_common_day_;
    delete rgb_line_;
    delete rgb_number_bright_;
    delete rgb_number_dark_;
  }
}

void CalendarConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CalendarConfig::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CalendarConfig_descriptor_;
}

const CalendarConfig& CalendarConfig::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_config_2eproto();
  return *default_instance_;
}

CalendarConfig* CalendarConfig::default_instance_ = NULL;

CalendarConfig* CalendarConfig::New(::google::protobuf::Arena* arena) const {
  CalendarConfig* n = new CalendarConfig;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CalendarConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:config.CalendarConfig)
  if (_has_bits_[0 / 32] & 253u) {
    num_years_ = 30;
    cell_size_ = 30;
    font_size_ = 15;
    line_width_ = 3;
    if (has_rgb_special_day()) {
      if (rgb_special_day_ != NULL) rgb_special_day_->::config::RGB::Clear();
    }
    if (has_rgb_sunday()) {
      if (rgb_sunday_ != NULL) rgb_sunday_->::config::RGB::Clear();
    }
    if (has_rgb_holiday()) {
      if (rgb_holiday_ != NULL) rgb_holiday_->::config::RGB::Clear();
    }
  }
  if (_has_bits_[8 / 32] & 3840u) {
    if (has_rgb_common_day()) {
      if (rgb_common_day_ != NULL) rgb_common_day_->::config::RGB::Clear();
    }
    if (has_rgb_line()) {
      if (rgb_line_ != NULL) rgb_line_->::config::RGB::Clear();
    }
    if (has_rgb_number_bright()) {
      if (rgb_number_bright_ != NULL) rgb_number_bright_->::config::RGB::Clear();
    }
    if (has_rgb_number_dark()) {
      if (rgb_number_dark_ != NULL) rgb_number_dark_->::config::RGB::Clear();
    }
  }
  special_day_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool CalendarConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:config.CalendarConfig)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 num_years = 1 [default = 30];
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &num_years_)));
          set_has_num_years();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_special_day;
        break;
      }

      // repeated .config.MonthDay special_day = 2;
      case 2: {
        if (tag == 18) {
         parse_special_day:
          DO_(input->IncrementRecursionDepth());
         parse_loop_special_day:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_special_day()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_loop_special_day;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectTag(24)) goto parse_cell_size;
        break;
      }

      // optional int32 cell_size = 3 [default = 30];
      case 3: {
        if (tag == 24) {
         parse_cell_size:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &cell_size_)));
          set_has_cell_size();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_font_size;
        break;
      }

      // optional int32 font_size = 4 [default = 15];
      case 4: {
        if (tag == 32) {
         parse_font_size:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &font_size_)));
          set_has_font_size();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_line_width;
        break;
      }

      // optional int32 line_width = 5 [default = 3];
      case 5: {
        if (tag == 40) {
         parse_line_width:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &line_width_)));
          set_has_line_width();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_rgb_special_day;
        break;
      }

      // optional .config.RGB rgb_special_day = 6;
      case 6: {
        if (tag == 50) {
         parse_rgb_special_day:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_rgb_special_day()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_rgb_sunday;
        break;
      }

      // optional .config.RGB rgb_sunday = 7;
      case 7: {
        if (tag == 58) {
         parse_rgb_sunday:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_rgb_sunday()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(66)) goto parse_rgb_holiday;
        break;
      }

      // optional .config.RGB rgb_holiday = 8;
      case 8: {
        if (tag == 66) {
         parse_rgb_holiday:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_rgb_holiday()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(74)) goto parse_rgb_common_day;
        break;
      }

      // optional .config.RGB rgb_common_day = 9;
      case 9: {
        if (tag == 74) {
         parse_rgb_common_day:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_rgb_common_day()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(82)) goto parse_rgb_line;
        break;
      }

      // optional .config.RGB rgb_line = 10;
      case 10: {
        if (tag == 82) {
         parse_rgb_line:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_rgb_line()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(90)) goto parse_rgb_number_bright;
        break;
      }

      // optional .config.RGB rgb_number_bright = 11;
      case 11: {
        if (tag == 90) {
         parse_rgb_number_bright:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_rgb_number_bright()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(98)) goto parse_rgb_number_dark;
        break;
      }

      // optional .config.RGB rgb_number_dark = 12;
      case 12: {
        if (tag == 98) {
         parse_rgb_number_dark:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_rgb_number_dark()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:config.CalendarConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:config.CalendarConfig)
  return false;
#undef DO_
}

void CalendarConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:config.CalendarConfig)
  // optional int32 num_years = 1 [default = 30];
  if (has_num_years()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->num_years(), output);
  }

  // repeated .config.MonthDay special_day = 2;
  for (unsigned int i = 0, n = this->special_day_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->special_day(i), output);
  }

  // optional int32 cell_size = 3 [default = 30];
  if (has_cell_size()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->cell_size(), output);
  }

  // optional int32 font_size = 4 [default = 15];
  if (has_font_size()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->font_size(), output);
  }

  // optional int32 line_width = 5 [default = 3];
  if (has_line_width()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->line_width(), output);
  }

  // optional .config.RGB rgb_special_day = 6;
  if (has_rgb_special_day()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, *this->rgb_special_day_, output);
  }

  // optional .config.RGB rgb_sunday = 7;
  if (has_rgb_sunday()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, *this->rgb_sunday_, output);
  }

  // optional .config.RGB rgb_holiday = 8;
  if (has_rgb_holiday()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      8, *this->rgb_holiday_, output);
  }

  // optional .config.RGB rgb_common_day = 9;
  if (has_rgb_common_day()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      9, *this->rgb_common_day_, output);
  }

  // optional .config.RGB rgb_line = 10;
  if (has_rgb_line()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      10, *this->rgb_line_, output);
  }

  // optional .config.RGB rgb_number_bright = 11;
  if (has_rgb_number_bright()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      11, *this->rgb_number_bright_, output);
  }

  // optional .config.RGB rgb_number_dark = 12;
  if (has_rgb_number_dark()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      12, *this->rgb_number_dark_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:config.CalendarConfig)
}

::google::protobuf::uint8* CalendarConfig::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:config.CalendarConfig)
  // optional int32 num_years = 1 [default = 30];
  if (has_num_years()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->num_years(), target);
  }

  // repeated .config.MonthDay special_day = 2;
  for (unsigned int i = 0, n = this->special_day_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->special_day(i), false, target);
  }

  // optional int32 cell_size = 3 [default = 30];
  if (has_cell_size()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->cell_size(), target);
  }

  // optional int32 font_size = 4 [default = 15];
  if (has_font_size()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->font_size(), target);
  }

  // optional int32 line_width = 5 [default = 3];
  if (has_line_width()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->line_width(), target);
  }

  // optional .config.RGB rgb_special_day = 6;
  if (has_rgb_special_day()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        6, *this->rgb_special_day_, false, target);
  }

  // optional .config.RGB rgb_sunday = 7;
  if (has_rgb_sunday()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        7, *this->rgb_sunday_, false, target);
  }

  // optional .config.RGB rgb_holiday = 8;
  if (has_rgb_holiday()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        8, *this->rgb_holiday_, false, target);
  }

  // optional .config.RGB rgb_common_day = 9;
  if (has_rgb_common_day()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        9, *this->rgb_common_day_, false, target);
  }

  // optional .config.RGB rgb_line = 10;
  if (has_rgb_line()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        10, *this->rgb_line_, false, target);
  }

  // optional .config.RGB rgb_number_bright = 11;
  if (has_rgb_number_bright()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        11, *this->rgb_number_bright_, false, target);
  }

  // optional .config.RGB rgb_number_dark = 12;
  if (has_rgb_number_dark()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        12, *this->rgb_number_dark_, false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:config.CalendarConfig)
  return target;
}

int CalendarConfig::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:config.CalendarConfig)
  int total_size = 0;

  if (_has_bits_[0 / 32] & 253u) {
    // optional int32 num_years = 1 [default = 30];
    if (has_num_years()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->num_years());
    }

    // optional int32 cell_size = 3 [default = 30];
    if (has_cell_size()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->cell_size());
    }

    // optional int32 font_size = 4 [default = 15];
    if (has_font_size()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->font_size());
    }

    // optional int32 line_width = 5 [default = 3];
    if (has_line_width()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->line_width());
    }

    // optional .config.RGB rgb_special_day = 6;
    if (has_rgb_special_day()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->rgb_special_day_);
    }

    // optional .config.RGB rgb_sunday = 7;
    if (has_rgb_sunday()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->rgb_sunday_);
    }

    // optional .config.RGB rgb_holiday = 8;
    if (has_rgb_holiday()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->rgb_holiday_);
    }

  }
  if (_has_bits_[8 / 32] & 3840u) {
    // optional .config.RGB rgb_common_day = 9;
    if (has_rgb_common_day()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->rgb_common_day_);
    }

    // optional .config.RGB rgb_line = 10;
    if (has_rgb_line()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->rgb_line_);
    }

    // optional .config.RGB rgb_number_bright = 11;
    if (has_rgb_number_bright()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->rgb_number_bright_);
    }

    // optional .config.RGB rgb_number_dark = 12;
    if (has_rgb_number_dark()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->rgb_number_dark_);
    }

  }
  // repeated .config.MonthDay special_day = 2;
  total_size += 1 * this->special_day_size();
  for (int i = 0; i < this->special_day_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->special_day(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CalendarConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:config.CalendarConfig)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const CalendarConfig* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CalendarConfig>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:config.CalendarConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:config.CalendarConfig)
    MergeFrom(*source);
  }
}

void CalendarConfig::MergeFrom(const CalendarConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:config.CalendarConfig)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  special_day_.MergeFrom(from.special_day_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_num_years()) {
      set_num_years(from.num_years());
    }
    if (from.has_cell_size()) {
      set_cell_size(from.cell_size());
    }
    if (from.has_font_size()) {
      set_font_size(from.font_size());
    }
    if (from.has_line_width()) {
      set_line_width(from.line_width());
    }
    if (from.has_rgb_special_day()) {
      mutable_rgb_special_day()->::config::RGB::MergeFrom(from.rgb_special_day());
    }
    if (from.has_rgb_sunday()) {
      mutable_rgb_sunday()->::config::RGB::MergeFrom(from.rgb_sunday());
    }
    if (from.has_rgb_holiday()) {
      mutable_rgb_holiday()->::config::RGB::MergeFrom(from.rgb_holiday());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_rgb_common_day()) {
      mutable_rgb_common_day()->::config::RGB::MergeFrom(from.rgb_common_day());
    }
    if (from.has_rgb_line()) {
      mutable_rgb_line()->::config::RGB::MergeFrom(from.rgb_line());
    }
    if (from.has_rgb_number_bright()) {
      mutable_rgb_number_bright()->::config::RGB::MergeFrom(from.rgb_number_bright());
    }
    if (from.has_rgb_number_dark()) {
      mutable_rgb_number_dark()->::config::RGB::MergeFrom(from.rgb_number_dark());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void CalendarConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:config.CalendarConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CalendarConfig::CopyFrom(const CalendarConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:config.CalendarConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CalendarConfig::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->special_day())) return false;
  if (has_rgb_special_day()) {
    if (!this->rgb_special_day_->IsInitialized()) return false;
  }
  if (has_rgb_sunday()) {
    if (!this->rgb_sunday_->IsInitialized()) return false;
  }
  if (has_rgb_holiday()) {
    if (!this->rgb_holiday_->IsInitialized()) return false;
  }
  if (has_rgb_common_day()) {
    if (!this->rgb_common_day_->IsInitialized()) return false;
  }
  if (has_rgb_line()) {
    if (!this->rgb_line_->IsInitialized()) return false;
  }
  if (has_rgb_number_bright()) {
    if (!this->rgb_number_bright_->IsInitialized()) return false;
  }
  if (has_rgb_number_dark()) {
    if (!this->rgb_number_dark_->IsInitialized()) return false;
  }
  return true;
}

void CalendarConfig::Swap(CalendarConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CalendarConfig::InternalSwap(CalendarConfig* other) {
  std::swap(num_years_, other->num_years_);
  special_day_.UnsafeArenaSwap(&other->special_day_);
  std::swap(cell_size_, other->cell_size_);
  std::swap(font_size_, other->font_size_);
  std::swap(line_width_, other->line_width_);
  std::swap(rgb_special_day_, other->rgb_special_day_);
  std::swap(rgb_sunday_, other->rgb_sunday_);
  std::swap(rgb_holiday_, other->rgb_holiday_);
  std::swap(rgb_common_day_, other->rgb_common_day_);
  std::swap(rgb_line_, other->rgb_line_);
  std::swap(rgb_number_bright_, other->rgb_number_bright_);
  std::swap(rgb_number_dark_, other->rgb_number_dark_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CalendarConfig::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CalendarConfig_descriptor_;
  metadata.reflection = CalendarConfig_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CalendarConfig

// optional int32 num_years = 1 [default = 30];
bool CalendarConfig::has_num_years() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void CalendarConfig::set_has_num_years() {
  _has_bits_[0] |= 0x00000001u;
}
void CalendarConfig::clear_has_num_years() {
  _has_bits_[0] &= ~0x00000001u;
}
void CalendarConfig::clear_num_years() {
  num_years_ = 30;
  clear_has_num_years();
}
 ::google::protobuf::int32 CalendarConfig::num_years() const {
  // @@protoc_insertion_point(field_get:config.CalendarConfig.num_years)
  return num_years_;
}
 void CalendarConfig::set_num_years(::google::protobuf::int32 value) {
  set_has_num_years();
  num_years_ = value;
  // @@protoc_insertion_point(field_set:config.CalendarConfig.num_years)
}

// repeated .config.MonthDay special_day = 2;
int CalendarConfig::special_day_size() const {
  return special_day_.size();
}
void CalendarConfig::clear_special_day() {
  special_day_.Clear();
}
const ::config::MonthDay& CalendarConfig::special_day(int index) const {
  // @@protoc_insertion_point(field_get:config.CalendarConfig.special_day)
  return special_day_.Get(index);
}
::config::MonthDay* CalendarConfig::mutable_special_day(int index) {
  // @@protoc_insertion_point(field_mutable:config.CalendarConfig.special_day)
  return special_day_.Mutable(index);
}
::config::MonthDay* CalendarConfig::add_special_day() {
  // @@protoc_insertion_point(field_add:config.CalendarConfig.special_day)
  return special_day_.Add();
}
::google::protobuf::RepeatedPtrField< ::config::MonthDay >*
CalendarConfig::mutable_special_day() {
  // @@protoc_insertion_point(field_mutable_list:config.CalendarConfig.special_day)
  return &special_day_;
}
const ::google::protobuf::RepeatedPtrField< ::config::MonthDay >&
CalendarConfig::special_day() const {
  // @@protoc_insertion_point(field_list:config.CalendarConfig.special_day)
  return special_day_;
}

// optional int32 cell_size = 3 [default = 30];
bool CalendarConfig::has_cell_size() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void CalendarConfig::set_has_cell_size() {
  _has_bits_[0] |= 0x00000004u;
}
void CalendarConfig::clear_has_cell_size() {
  _has_bits_[0] &= ~0x00000004u;
}
void CalendarConfig::clear_cell_size() {
  cell_size_ = 30;
  clear_has_cell_size();
}
 ::google::protobuf::int32 CalendarConfig::cell_size() const {
  // @@protoc_insertion_point(field_get:config.CalendarConfig.cell_size)
  return cell_size_;
}
 void CalendarConfig::set_cell_size(::google::protobuf::int32 value) {
  set_has_cell_size();
  cell_size_ = value;
  // @@protoc_insertion_point(field_set:config.CalendarConfig.cell_size)
}

// optional int32 font_size = 4 [default = 15];
bool CalendarConfig::has_font_size() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void CalendarConfig::set_has_font_size() {
  _has_bits_[0] |= 0x00000008u;
}
void CalendarConfig::clear_has_font_size() {
  _has_bits_[0] &= ~0x00000008u;
}
void CalendarConfig::clear_font_size() {
  font_size_ = 15;
  clear_has_font_size();
}
 ::google::protobuf::int32 CalendarConfig::font_size() const {
  // @@protoc_insertion_point(field_get:config.CalendarConfig.font_size)
  return font_size_;
}
 void CalendarConfig::set_font_size(::google::protobuf::int32 value) {
  set_has_font_size();
  font_size_ = value;
  // @@protoc_insertion_point(field_set:config.CalendarConfig.font_size)
}

// optional int32 line_width = 5 [default = 3];
bool CalendarConfig::has_line_width() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void CalendarConfig::set_has_line_width() {
  _has_bits_[0] |= 0x00000010u;
}
void CalendarConfig::clear_has_line_width() {
  _has_bits_[0] &= ~0x00000010u;
}
void CalendarConfig::clear_line_width() {
  line_width_ = 3;
  clear_has_line_width();
}
 ::google::protobuf::int32 CalendarConfig::line_width() const {
  // @@protoc_insertion_point(field_get:config.CalendarConfig.line_width)
  return line_width_;
}
 void CalendarConfig::set_line_width(::google::protobuf::int32 value) {
  set_has_line_width();
  line_width_ = value;
  // @@protoc_insertion_point(field_set:config.CalendarConfig.line_width)
}

// optional .config.RGB rgb_special_day = 6;
bool CalendarConfig::has_rgb_special_day() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void CalendarConfig::set_has_rgb_special_day() {
  _has_bits_[0] |= 0x00000020u;
}
void CalendarConfig::clear_has_rgb_special_day() {
  _has_bits_[0] &= ~0x00000020u;
}
void CalendarConfig::clear_rgb_special_day() {
  if (rgb_special_day_ != NULL) rgb_special_day_->::config::RGB::Clear();
  clear_has_rgb_special_day();
}
const ::config::RGB& CalendarConfig::rgb_special_day() const {
  // @@protoc_insertion_point(field_get:config.CalendarConfig.rgb_special_day)
  return rgb_special_day_ != NULL ? *rgb_special_day_ : *default_instance_->rgb_special_day_;
}
::config::RGB* CalendarConfig::mutable_rgb_special_day() {
  set_has_rgb_special_day();
  if (rgb_special_day_ == NULL) {
    rgb_special_day_ = new ::config::RGB;
  }
  // @@protoc_insertion_point(field_mutable:config.CalendarConfig.rgb_special_day)
  return rgb_special_day_;
}
::config::RGB* CalendarConfig::release_rgb_special_day() {
  // @@protoc_insertion_point(field_release:config.CalendarConfig.rgb_special_day)
  clear_has_rgb_special_day();
  ::config::RGB* temp = rgb_special_day_;
  rgb_special_day_ = NULL;
  return temp;
}
void CalendarConfig::set_allocated_rgb_special_day(::config::RGB* rgb_special_day) {
  delete rgb_special_day_;
  rgb_special_day_ = rgb_special_day;
  if (rgb_special_day) {
    set_has_rgb_special_day();
  } else {
    clear_has_rgb_special_day();
  }
  // @@protoc_insertion_point(field_set_allocated:config.CalendarConfig.rgb_special_day)
}

// optional .config.RGB rgb_sunday = 7;
bool CalendarConfig::has_rgb_sunday() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
void CalendarConfig::set_has_rgb_sunday() {
  _has_bits_[0] |= 0x00000040u;
}
void CalendarConfig::clear_has_rgb_sunday() {
  _has_bits_[0] &= ~0x00000040u;
}
void CalendarConfig::clear_rgb_sunday() {
  if (rgb_sunday_ != NULL) rgb_sunday_->::config::RGB::Clear();
  clear_has_rgb_sunday();
}
const ::config::RGB& CalendarConfig::rgb_sunday() const {
  // @@protoc_insertion_point(field_get:config.CalendarConfig.rgb_sunday)
  return rgb_sunday_ != NULL ? *rgb_sunday_ : *default_instance_->rgb_sunday_;
}
::config::RGB* CalendarConfig::mutable_rgb_sunday() {
  set_has_rgb_sunday();
  if (rgb_sunday_ == NULL) {
    rgb_sunday_ = new ::config::RGB;
  }
  // @@protoc_insertion_point(field_mutable:config.CalendarConfig.rgb_sunday)
  return rgb_sunday_;
}
::config::RGB* CalendarConfig::release_rgb_sunday() {
  // @@protoc_insertion_point(field_release:config.CalendarConfig.rgb_sunday)
  clear_has_rgb_sunday();
  ::config::RGB* temp = rgb_sunday_;
  rgb_sunday_ = NULL;
  return temp;
}
void CalendarConfig::set_allocated_rgb_sunday(::config::RGB* rgb_sunday) {
  delete rgb_sunday_;
  rgb_sunday_ = rgb_sunday;
  if (rgb_sunday) {
    set_has_rgb_sunday();
  } else {
    clear_has_rgb_sunday();
  }
  // @@protoc_insertion_point(field_set_allocated:config.CalendarConfig.rgb_sunday)
}

// optional .config.RGB rgb_holiday = 8;
bool CalendarConfig::has_rgb_holiday() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
void CalendarConfig::set_has_rgb_holiday() {
  _has_bits_[0] |= 0x00000080u;
}
void CalendarConfig::clear_has_rgb_holiday() {
  _has_bits_[0] &= ~0x00000080u;
}
void CalendarConfig::clear_rgb_holiday() {
  if (rgb_holiday_ != NULL) rgb_holiday_->::config::RGB::Clear();
  clear_has_rgb_holiday();
}
const ::config::RGB& CalendarConfig::rgb_holiday() const {
  // @@protoc_insertion_point(field_get:config.CalendarConfig.rgb_holiday)
  return rgb_holiday_ != NULL ? *rgb_holiday_ : *default_instance_->rgb_holiday_;
}
::config::RGB* CalendarConfig::mutable_rgb_holiday() {
  set_has_rgb_holiday();
  if (rgb_holiday_ == NULL) {
    rgb_holiday_ = new ::config::RGB;
  }
  // @@protoc_insertion_point(field_mutable:config.CalendarConfig.rgb_holiday)
  return rgb_holiday_;
}
::config::RGB* CalendarConfig::release_rgb_holiday() {
  // @@protoc_insertion_point(field_release:config.CalendarConfig.rgb_holiday)
  clear_has_rgb_holiday();
  ::config::RGB* temp = rgb_holiday_;
  rgb_holiday_ = NULL;
  return temp;
}
void CalendarConfig::set_allocated_rgb_holiday(::config::RGB* rgb_holiday) {
  delete rgb_holiday_;
  rgb_holiday_ = rgb_holiday;
  if (rgb_holiday) {
    set_has_rgb_holiday();
  } else {
    clear_has_rgb_holiday();
  }
  // @@protoc_insertion_point(field_set_allocated:config.CalendarConfig.rgb_holiday)
}

// optional .config.RGB rgb_common_day = 9;
bool CalendarConfig::has_rgb_common_day() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
void CalendarConfig::set_has_rgb_common_day() {
  _has_bits_[0] |= 0x00000100u;
}
void CalendarConfig::clear_has_rgb_common_day() {
  _has_bits_[0] &= ~0x00000100u;
}
void CalendarConfig::clear_rgb_common_day() {
  if (rgb_common_day_ != NULL) rgb_common_day_->::config::RGB::Clear();
  clear_has_rgb_common_day();
}
const ::config::RGB& CalendarConfig::rgb_common_day() const {
  // @@protoc_insertion_point(field_get:config.CalendarConfig.rgb_common_day)
  return rgb_common_day_ != NULL ? *rgb_common_day_ : *default_instance_->rgb_common_day_;
}
::config::RGB* CalendarConfig::mutable_rgb_common_day() {
  set_has_rgb_common_day();
  if (rgb_common_day_ == NULL) {
    rgb_common_day_ = new ::config::RGB;
  }
  // @@protoc_insertion_point(field_mutable:config.CalendarConfig.rgb_common_day)
  return rgb_common_day_;
}
::config::RGB* CalendarConfig::release_rgb_common_day() {
  // @@protoc_insertion_point(field_release:config.CalendarConfig.rgb_common_day)
  clear_has_rgb_common_day();
  ::config::RGB* temp = rgb_common_day_;
  rgb_common_day_ = NULL;
  return temp;
}
void CalendarConfig::set_allocated_rgb_common_day(::config::RGB* rgb_common_day) {
  delete rgb_common_day_;
  rgb_common_day_ = rgb_common_day;
  if (rgb_common_day) {
    set_has_rgb_common_day();
  } else {
    clear_has_rgb_common_day();
  }
  // @@protoc_insertion_point(field_set_allocated:config.CalendarConfig.rgb_common_day)
}

// optional .config.RGB rgb_line = 10;
bool CalendarConfig::has_rgb_line() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
void CalendarConfig::set_has_rgb_line() {
  _has_bits_[0] |= 0x00000200u;
}
void CalendarConfig::clear_has_rgb_line() {
  _has_bits_[0] &= ~0x00000200u;
}
void CalendarConfig::clear_rgb_line() {
  if (rgb_line_ != NULL) rgb_line_->::config::RGB::Clear();
  clear_has_rgb_line();
}
const ::config::RGB& CalendarConfig::rgb_line() const {
  // @@protoc_insertion_point(field_get:config.CalendarConfig.rgb_line)
  return rgb_line_ != NULL ? *rgb_line_ : *default_instance_->rgb_line_;
}
::config::RGB* CalendarConfig::mutable_rgb_line() {
  set_has_rgb_line();
  if (rgb_line_ == NULL) {
    rgb_line_ = new ::config::RGB;
  }
  // @@protoc_insertion_point(field_mutable:config.CalendarConfig.rgb_line)
  return rgb_line_;
}
::config::RGB* CalendarConfig::release_rgb_line() {
  // @@protoc_insertion_point(field_release:config.CalendarConfig.rgb_line)
  clear_has_rgb_line();
  ::config::RGB* temp = rgb_line_;
  rgb_line_ = NULL;
  return temp;
}
void CalendarConfig::set_allocated_rgb_line(::config::RGB* rgb_line) {
  delete rgb_line_;
  rgb_line_ = rgb_line;
  if (rgb_line) {
    set_has_rgb_line();
  } else {
    clear_has_rgb_line();
  }
  // @@protoc_insertion_point(field_set_allocated:config.CalendarConfig.rgb_line)
}

// optional .config.RGB rgb_number_bright = 11;
bool CalendarConfig::has_rgb_number_bright() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
void CalendarConfig::set_has_rgb_number_bright() {
  _has_bits_[0] |= 0x00000400u;
}
void CalendarConfig::clear_has_rgb_number_bright() {
  _has_bits_[0] &= ~0x00000400u;
}
void CalendarConfig::clear_rgb_number_bright() {
  if (rgb_number_bright_ != NULL) rgb_number_bright_->::config::RGB::Clear();
  clear_has_rgb_number_bright();
}
const ::config::RGB& CalendarConfig::rgb_number_bright() const {
  // @@protoc_insertion_point(field_get:config.CalendarConfig.rgb_number_bright)
  return rgb_number_bright_ != NULL ? *rgb_number_bright_ : *default_instance_->rgb_number_bright_;
}
::config::RGB* CalendarConfig::mutable_rgb_number_bright() {
  set_has_rgb_number_bright();
  if (rgb_number_bright_ == NULL) {
    rgb_number_bright_ = new ::config::RGB;
  }
  // @@protoc_insertion_point(field_mutable:config.CalendarConfig.rgb_number_bright)
  return rgb_number_bright_;
}
::config::RGB* CalendarConfig::release_rgb_number_bright() {
  // @@protoc_insertion_point(field_release:config.CalendarConfig.rgb_number_bright)
  clear_has_rgb_number_bright();
  ::config::RGB* temp = rgb_number_bright_;
  rgb_number_bright_ = NULL;
  return temp;
}
void CalendarConfig::set_allocated_rgb_number_bright(::config::RGB* rgb_number_bright) {
  delete rgb_number_bright_;
  rgb_number_bright_ = rgb_number_bright;
  if (rgb_number_bright) {
    set_has_rgb_number_bright();
  } else {
    clear_has_rgb_number_bright();
  }
  // @@protoc_insertion_point(field_set_allocated:config.CalendarConfig.rgb_number_bright)
}

// optional .config.RGB rgb_number_dark = 12;
bool CalendarConfig::has_rgb_number_dark() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
void CalendarConfig::set_has_rgb_number_dark() {
  _has_bits_[0] |= 0x00000800u;
}
void CalendarConfig::clear_has_rgb_number_dark() {
  _has_bits_[0] &= ~0x00000800u;
}
void CalendarConfig::clear_rgb_number_dark() {
  if (rgb_number_dark_ != NULL) rgb_number_dark_->::config::RGB::Clear();
  clear_has_rgb_number_dark();
}
const ::config::RGB& CalendarConfig::rgb_number_dark() const {
  // @@protoc_insertion_point(field_get:config.CalendarConfig.rgb_number_dark)
  return rgb_number_dark_ != NULL ? *rgb_number_dark_ : *default_instance_->rgb_number_dark_;
}
::config::RGB* CalendarConfig::mutable_rgb_number_dark() {
  set_has_rgb_number_dark();
  if (rgb_number_dark_ == NULL) {
    rgb_number_dark_ = new ::config::RGB;
  }
  // @@protoc_insertion_point(field_mutable:config.CalendarConfig.rgb_number_dark)
  return rgb_number_dark_;
}
::config::RGB* CalendarConfig::release_rgb_number_dark() {
  // @@protoc_insertion_point(field_release:config.CalendarConfig.rgb_number_dark)
  clear_has_rgb_number_dark();
  ::config::RGB* temp = rgb_number_dark_;
  rgb_number_dark_ = NULL;
  return temp;
}
void CalendarConfig::set_allocated_rgb_number_dark(::config::RGB* rgb_number_dark) {
  delete rgb_number_dark_;
  rgb_number_dark_ = rgb_number_dark;
  if (rgb_number_dark) {
    set_has_rgb_number_dark();
  } else {
    clear_has_rgb_number_dark();
  }
  // @@protoc_insertion_point(field_set_allocated:config.CalendarConfig.rgb_number_dark)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MonthDay::kMonthFieldNumber;
const int MonthDay::kDayFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MonthDay::MonthDay()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:config.MonthDay)
}

void MonthDay::InitAsDefaultInstance() {
}

MonthDay::MonthDay(const MonthDay& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:config.MonthDay)
}

void MonthDay::SharedCtor() {
  _cached_size_ = 0;
  month_ = 0;
  day_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MonthDay::~MonthDay() {
  // @@protoc_insertion_point(destructor:config.MonthDay)
  SharedDtor();
}

void MonthDay::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MonthDay::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MonthDay::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MonthDay_descriptor_;
}

const MonthDay& MonthDay::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_config_2eproto();
  return *default_instance_;
}

MonthDay* MonthDay::default_instance_ = NULL;

MonthDay* MonthDay::New(::google::protobuf::Arena* arena) const {
  MonthDay* n = new MonthDay;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MonthDay::Clear() {
// @@protoc_insertion_point(message_clear_start:config.MonthDay)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(MonthDay, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<MonthDay*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(month_, day_);

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool MonthDay::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:config.MonthDay)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 month = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &month_)));
          set_has_month();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_day;
        break;
      }

      // required int32 day = 2;
      case 2: {
        if (tag == 16) {
         parse_day:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &day_)));
          set_has_day();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:config.MonthDay)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:config.MonthDay)
  return false;
#undef DO_
}

void MonthDay::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:config.MonthDay)
  // required int32 month = 1;
  if (has_month()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->month(), output);
  }

  // required int32 day = 2;
  if (has_day()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->day(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:config.MonthDay)
}

::google::protobuf::uint8* MonthDay::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:config.MonthDay)
  // required int32 month = 1;
  if (has_month()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->month(), target);
  }

  // required int32 day = 2;
  if (has_day()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->day(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:config.MonthDay)
  return target;
}

int MonthDay::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:config.MonthDay)
  int total_size = 0;

  if (has_month()) {
    // required int32 month = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->month());
  }

  if (has_day()) {
    // required int32 day = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->day());
  }

  return total_size;
}
int MonthDay::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:config.MonthDay)
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required int32 month = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->month());

    // required int32 day = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->day());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MonthDay::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:config.MonthDay)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const MonthDay* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const MonthDay>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:config.MonthDay)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:config.MonthDay)
    MergeFrom(*source);
  }
}

void MonthDay::MergeFrom(const MonthDay& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:config.MonthDay)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_month()) {
      set_month(from.month());
    }
    if (from.has_day()) {
      set_day(from.day());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void MonthDay::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:config.MonthDay)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MonthDay::CopyFrom(const MonthDay& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:config.MonthDay)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MonthDay::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void MonthDay::Swap(MonthDay* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MonthDay::InternalSwap(MonthDay* other) {
  std::swap(month_, other->month_);
  std::swap(day_, other->day_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MonthDay::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MonthDay_descriptor_;
  metadata.reflection = MonthDay_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MonthDay

// required int32 month = 1;
bool MonthDay::has_month() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void MonthDay::set_has_month() {
  _has_bits_[0] |= 0x00000001u;
}
void MonthDay::clear_has_month() {
  _has_bits_[0] &= ~0x00000001u;
}
void MonthDay::clear_month() {
  month_ = 0;
  clear_has_month();
}
 ::google::protobuf::int32 MonthDay::month() const {
  // @@protoc_insertion_point(field_get:config.MonthDay.month)
  return month_;
}
 void MonthDay::set_month(::google::protobuf::int32 value) {
  set_has_month();
  month_ = value;
  // @@protoc_insertion_point(field_set:config.MonthDay.month)
}

// required int32 day = 2;
bool MonthDay::has_day() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void MonthDay::set_has_day() {
  _has_bits_[0] |= 0x00000002u;
}
void MonthDay::clear_has_day() {
  _has_bits_[0] &= ~0x00000002u;
}
void MonthDay::clear_day() {
  day_ = 0;
  clear_has_day();
}
 ::google::protobuf::int32 MonthDay::day() const {
  // @@protoc_insertion_point(field_get:config.MonthDay.day)
  return day_;
}
 void MonthDay::set_day(::google::protobuf::int32 value) {
  set_has_day();
  day_ = value;
  // @@protoc_insertion_point(field_set:config.MonthDay.day)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RGB::kRedFieldNumber;
const int RGB::kGreenFieldNumber;
const int RGB::kBlueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RGB::RGB()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:config.RGB)
}

void RGB::InitAsDefaultInstance() {
}

RGB::RGB(const RGB& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:config.RGB)
}

void RGB::SharedCtor() {
  _cached_size_ = 0;
  red_ = 0;
  green_ = 0;
  blue_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RGB::~RGB() {
  // @@protoc_insertion_point(destructor:config.RGB)
  SharedDtor();
}

void RGB::SharedDtor() {
  if (this != default_instance_) {
  }
}

void RGB::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RGB::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RGB_descriptor_;
}

const RGB& RGB::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_config_2eproto();
  return *default_instance_;
}

RGB* RGB::default_instance_ = NULL;

RGB* RGB::New(::google::protobuf::Arena* arena) const {
  RGB* n = new RGB;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RGB::Clear() {
// @@protoc_insertion_point(message_clear_start:config.RGB)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(RGB, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<RGB*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(red_, blue_);

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool RGB::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:config.RGB)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 red = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &red_)));
          set_has_red();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_green;
        break;
      }

      // required int32 green = 2;
      case 2: {
        if (tag == 16) {
         parse_green:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &green_)));
          set_has_green();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_blue;
        break;
      }

      // required int32 blue = 3;
      case 3: {
        if (tag == 24) {
         parse_blue:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &blue_)));
          set_has_blue();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:config.RGB)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:config.RGB)
  return false;
#undef DO_
}

void RGB::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:config.RGB)
  // required int32 red = 1;
  if (has_red()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->red(), output);
  }

  // required int32 green = 2;
  if (has_green()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->green(), output);
  }

  // required int32 blue = 3;
  if (has_blue()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->blue(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:config.RGB)
}

::google::protobuf::uint8* RGB::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:config.RGB)
  // required int32 red = 1;
  if (has_red()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->red(), target);
  }

  // required int32 green = 2;
  if (has_green()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->green(), target);
  }

  // required int32 blue = 3;
  if (has_blue()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->blue(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:config.RGB)
  return target;
}

int RGB::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:config.RGB)
  int total_size = 0;

  if (has_red()) {
    // required int32 red = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->red());
  }

  if (has_green()) {
    // required int32 green = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->green());
  }

  if (has_blue()) {
    // required int32 blue = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->blue());
  }

  return total_size;
}
int RGB::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:config.RGB)
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required int32 red = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->red());

    // required int32 green = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->green());

    // required int32 blue = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->blue());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RGB::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:config.RGB)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const RGB* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const RGB>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:config.RGB)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:config.RGB)
    MergeFrom(*source);
  }
}

void RGB::MergeFrom(const RGB& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:config.RGB)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_red()) {
      set_red(from.red());
    }
    if (from.has_green()) {
      set_green(from.green());
    }
    if (from.has_blue()) {
      set_blue(from.blue());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void RGB::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:config.RGB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RGB::CopyFrom(const RGB& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:config.RGB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RGB::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void RGB::Swap(RGB* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RGB::InternalSwap(RGB* other) {
  std::swap(red_, other->red_);
  std::swap(green_, other->green_);
  std::swap(blue_, other->blue_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata RGB::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RGB_descriptor_;
  metadata.reflection = RGB_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RGB

// required int32 red = 1;
bool RGB::has_red() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void RGB::set_has_red() {
  _has_bits_[0] |= 0x00000001u;
}
void RGB::clear_has_red() {
  _has_bits_[0] &= ~0x00000001u;
}
void RGB::clear_red() {
  red_ = 0;
  clear_has_red();
}
 ::google::protobuf::int32 RGB::red() const {
  // @@protoc_insertion_point(field_get:config.RGB.red)
  return red_;
}
 void RGB::set_red(::google::protobuf::int32 value) {
  set_has_red();
  red_ = value;
  // @@protoc_insertion_point(field_set:config.RGB.red)
}

// required int32 green = 2;
bool RGB::has_green() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void RGB::set_has_green() {
  _has_bits_[0] |= 0x00000002u;
}
void RGB::clear_has_green() {
  _has_bits_[0] &= ~0x00000002u;
}
void RGB::clear_green() {
  green_ = 0;
  clear_has_green();
}
 ::google::protobuf::int32 RGB::green() const {
  // @@protoc_insertion_point(field_get:config.RGB.green)
  return green_;
}
 void RGB::set_green(::google::protobuf::int32 value) {
  set_has_green();
  green_ = value;
  // @@protoc_insertion_point(field_set:config.RGB.green)
}

// required int32 blue = 3;
bool RGB::has_blue() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void RGB::set_has_blue() {
  _has_bits_[0] |= 0x00000004u;
}
void RGB::clear_has_blue() {
  _has_bits_[0] &= ~0x00000004u;
}
void RGB::clear_blue() {
  blue_ = 0;
  clear_has_blue();
}
 ::google::protobuf::int32 RGB::blue() const {
  // @@protoc_insertion_point(field_get:config.RGB.blue)
  return blue_;
}
 void RGB::set_blue(::google::protobuf::int32 value) {
  set_has_blue();
  blue_ = value;
  // @@protoc_insertion_point(field_set:config.RGB.blue)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace config

// @@protoc_insertion_point(global_scope)
