// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

#include "config.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_config_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_config_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_RGB;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_config_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_SpecialDay;
}  // namespace protobuf_config_2eproto
namespace config {
class CalendarConfigDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CalendarConfig>
      _instance;
} _CalendarConfig_default_instance_;
class SpecialDayDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SpecialDay>
      _instance;
} _SpecialDay_default_instance_;
class RGBDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<RGB>
      _instance;
} _RGB_default_instance_;
}  // namespace config
namespace protobuf_config_2eproto {
static void InitDefaultsCalendarConfig() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::config::_CalendarConfig_default_instance_;
    new (ptr) ::config::CalendarConfig();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::config::CalendarConfig::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_CalendarConfig =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsCalendarConfig}, {
      &protobuf_config_2eproto::scc_info_SpecialDay.base,
      &protobuf_config_2eproto::scc_info_RGB.base,}};

static void InitDefaultsSpecialDay() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::config::_SpecialDay_default_instance_;
    new (ptr) ::config::SpecialDay();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::config::SpecialDay::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_SpecialDay =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsSpecialDay}, {
      &protobuf_config_2eproto::scc_info_RGB.base,}};

static void InitDefaultsRGB() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::config::_RGB_default_instance_;
    new (ptr) ::config::RGB();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::config::RGB::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_RGB =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsRGB}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_CalendarConfig.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SpecialDay.base);
  ::google::protobuf::internal::InitSCC(&scc_info_RGB.base);
}

::google::protobuf::Metadata file_level_metadata[3];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, num_years_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, first_month_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, num_months_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, special_day_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, cell_size_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, cell_margin_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, font_size_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, bigger_font_size_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, line_width_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, month_label_height_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, year_label_width_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, rgb_header_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, rgb_header_sunday_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, rgb_month_line_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, rgb_holiday_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, bottom_left_label_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, bottom_right_label_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, header_font_family_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, number_font_family_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, quote_font_family_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, dotted_line_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, vertical_dotted_line_x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::CalendarConfig, output_type_),
  20,
  21,
  19,
  ~0u,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  5,
  6,
  7,
  8,
  0,
  1,
  2,
  3,
  4,
  17,
  16,
  18,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::SpecialDay, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::SpecialDay, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::SpecialDay, month_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::SpecialDay, day_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::SpecialDay, svg_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::SpecialDay, first_year_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::SpecialDay, year_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::SpecialDay, rgb_),
  2,
  3,
  0,
  4,
  5,
  1,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::RGB, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::RGB, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::RGB, red_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::RGB, green_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::config::RGB, blue_),
  0,
  1,
  2,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 28, sizeof(::config::CalendarConfig)},
  { 51, 62, sizeof(::config::SpecialDay)},
  { 68, 76, sizeof(::config::RGB)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::config::_CalendarConfig_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::config::_SpecialDay_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::config::_RGB_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "config.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014config.proto\022\006config\"\243\005\n\016CalendarConfi"
      "g\022\025\n\tnum_years\030\001 \001(\005:\00230\022\026\n\013first_month\030"
      "\002 \001(\005:\0011\022\026\n\nnum_months\030\003 \001(\005:\00212\022\'\n\013spec"
      "ial_day\030\004 \003(\0132\022.config.SpecialDay\022\021\n\tcel"
      "l_size\030\005 \001(\001\022\023\n\013cell_margin\030\006 \001(\001\022\021\n\tfon"
      "t_size\030\007 \001(\001\022\030\n\020bigger_font_size\030\010 \001(\001\022\022"
      "\n\nline_width\030\t \001(\001\022\032\n\022month_label_height"
      "\030\n \001(\001\022\030\n\020year_label_width\030\013 \001(\001\022\037\n\nrgb_"
      "header\030\014 \001(\0132\013.config.RGB\022&\n\021rgb_header_"
      "sunday\030\r \001(\0132\013.config.RGB\022#\n\016rgb_month_l"
      "ine\030\016 \001(\0132\013.config.RGB\022 \n\013rgb_holiday\030\017 "
      "\001(\0132\013.config.RGB\022\031\n\021bottom_left_label\030\020 "
      "\001(\t\022\032\n\022bottom_right_label\030\021 \001(\t\022\032\n\022heade"
      "r_font_family\030\022 \001(\t\022\032\n\022number_font_famil"
      "y\030\023 \001(\t\022\031\n\021quote_font_family\030\024 \001(\t\022\032\n\013do"
      "tted_line\030\025 \001(\010:\005false\022\036\n\026vertical_dotte"
      "d_line_x\030\026 \001(\001\022,\n\013output_type\030\027 \001(\0162\022.co"
      "nfig.OutputType:\003SVG\"q\n\nSpecialDay\022\r\n\005mo"
      "nth\030\001 \002(\005\022\013\n\003day\030\002 \002(\005\022\013\n\003svg\030\003 \001(\t\022\022\n\nf"
      "irst_year\030\004 \001(\005\022\014\n\004year\030\005 \001(\005\022\030\n\003rgb\030\006 \001"
      "(\0132\013.config.RGB\"/\n\003RGB\022\013\n\003red\030\001 \002(\005\022\r\n\005g"
      "reen\030\002 \002(\005\022\014\n\004blue\030\003 \002(\005*\'\n\nOutputType\022\007"
      "\n\003SVG\020\000\022\007\n\003PDF\020\001\022\007\n\003PNG\020\002"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 905);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "config.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_config_2eproto
namespace config {
const ::google::protobuf::EnumDescriptor* OutputType_descriptor() {
  protobuf_config_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_config_2eproto::file_level_enum_descriptors[0];
}
bool OutputType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void CalendarConfig::InitAsDefaultInstance() {
  ::config::_CalendarConfig_default_instance_._instance.get_mutable()->rgb_header_ = const_cast< ::config::RGB*>(
      ::config::RGB::internal_default_instance());
  ::config::_CalendarConfig_default_instance_._instance.get_mutable()->rgb_header_sunday_ = const_cast< ::config::RGB*>(
      ::config::RGB::internal_default_instance());
  ::config::_CalendarConfig_default_instance_._instance.get_mutable()->rgb_month_line_ = const_cast< ::config::RGB*>(
      ::config::RGB::internal_default_instance());
  ::config::_CalendarConfig_default_instance_._instance.get_mutable()->rgb_holiday_ = const_cast< ::config::RGB*>(
      ::config::RGB::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CalendarConfig::kNumYearsFieldNumber;
const int CalendarConfig::kFirstMonthFieldNumber;
const int CalendarConfig::kNumMonthsFieldNumber;
const int CalendarConfig::kSpecialDayFieldNumber;
const int CalendarConfig::kCellSizeFieldNumber;
const int CalendarConfig::kCellMarginFieldNumber;
const int CalendarConfig::kFontSizeFieldNumber;
const int CalendarConfig::kBiggerFontSizeFieldNumber;
const int CalendarConfig::kLineWidthFieldNumber;
const int CalendarConfig::kMonthLabelHeightFieldNumber;
const int CalendarConfig::kYearLabelWidthFieldNumber;
const int CalendarConfig::kRgbHeaderFieldNumber;
const int CalendarConfig::kRgbHeaderSundayFieldNumber;
const int CalendarConfig::kRgbMonthLineFieldNumber;
const int CalendarConfig::kRgbHolidayFieldNumber;
const int CalendarConfig::kBottomLeftLabelFieldNumber;
const int CalendarConfig::kBottomRightLabelFieldNumber;
const int CalendarConfig::kHeaderFontFamilyFieldNumber;
const int CalendarConfig::kNumberFontFamilyFieldNumber;
const int CalendarConfig::kQuoteFontFamilyFieldNumber;
const int CalendarConfig::kDottedLineFieldNumber;
const int CalendarConfig::kVerticalDottedLineXFieldNumber;
const int CalendarConfig::kOutputTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CalendarConfig::CalendarConfig()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_config_2eproto::scc_info_CalendarConfig.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:config.CalendarConfig)
}
CalendarConfig::CalendarConfig(const CalendarConfig& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      special_day_(from.special_day_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  bottom_left_label_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_bottom_left_label()) {
    bottom_left_label_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bottom_left_label_);
  }
  bottom_right_label_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_bottom_right_label()) {
    bottom_right_label_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bottom_right_label_);
  }
  header_font_family_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_header_font_family()) {
    header_font_family_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.header_font_family_);
  }
  number_font_family_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_number_font_family()) {
    number_font_family_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.number_font_family_);
  }
  quote_font_family_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_quote_font_family()) {
    quote_font_family_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.quote_font_family_);
  }
  if (from.has_rgb_header()) {
    rgb_header_ = new ::config::RGB(*from.rgb_header_);
  } else {
    rgb_header_ = NULL;
  }
  if (from.has_rgb_header_sunday()) {
    rgb_header_sunday_ = new ::config::RGB(*from.rgb_header_sunday_);
  } else {
    rgb_header_sunday_ = NULL;
  }
  if (from.has_rgb_month_line()) {
    rgb_month_line_ = new ::config::RGB(*from.rgb_month_line_);
  } else {
    rgb_month_line_ = NULL;
  }
  if (from.has_rgb_holiday()) {
    rgb_holiday_ = new ::config::RGB(*from.rgb_holiday_);
  } else {
    rgb_holiday_ = NULL;
  }
  ::memcpy(&cell_size_, &from.cell_size_,
    static_cast<size_t>(reinterpret_cast<char*>(&first_month_) -
    reinterpret_cast<char*>(&cell_size_)) + sizeof(first_month_));
  // @@protoc_insertion_point(copy_constructor:config.CalendarConfig)
}

void CalendarConfig::SharedCtor() {
  bottom_left_label_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bottom_right_label_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  header_font_family_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  number_font_family_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  quote_font_family_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&rgb_header_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&output_type_) -
      reinterpret_cast<char*>(&rgb_header_)) + sizeof(output_type_));
  num_months_ = 12;
  num_years_ = 30;
  first_month_ = 1;
}

CalendarConfig::~CalendarConfig() {
  // @@protoc_insertion_point(destructor:config.CalendarConfig)
  SharedDtor();
}

void CalendarConfig::SharedDtor() {
  bottom_left_label_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bottom_right_label_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  header_font_family_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  number_font_family_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  quote_font_family_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete rgb_header_;
  if (this != internal_default_instance()) delete rgb_header_sunday_;
  if (this != internal_default_instance()) delete rgb_month_line_;
  if (this != internal_default_instance()) delete rgb_holiday_;
}

void CalendarConfig::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CalendarConfig::descriptor() {
  ::protobuf_config_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_config_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CalendarConfig& CalendarConfig::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_config_2eproto::scc_info_CalendarConfig.base);
  return *internal_default_instance();
}


void CalendarConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:config.CalendarConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  special_day_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 255u) {
    if (cached_has_bits & 0x00000001u) {
      bottom_left_label_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      bottom_right_label_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000004u) {
      header_font_family_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000008u) {
      number_font_family_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000010u) {
      quote_font_family_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000020u) {
      GOOGLE_DCHECK(rgb_header_ != NULL);
      rgb_header_->Clear();
    }
    if (cached_has_bits & 0x00000040u) {
      GOOGLE_DCHECK(rgb_header_sunday_ != NULL);
      rgb_header_sunday_->Clear();
    }
    if (cached_has_bits & 0x00000080u) {
      GOOGLE_DCHECK(rgb_month_line_ != NULL);
      rgb_month_line_->Clear();
    }
  }
  if (cached_has_bits & 0x00000100u) {
    GOOGLE_DCHECK(rgb_holiday_ != NULL);
    rgb_holiday_->Clear();
  }
  if (cached_has_bits & 65024u) {
    ::memset(&cell_size_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&year_label_width_) -
        reinterpret_cast<char*>(&cell_size_)) + sizeof(year_label_width_));
  }
  if (cached_has_bits & 4128768u) {
    ::memset(&vertical_dotted_line_x_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&output_type_) -
        reinterpret_cast<char*>(&vertical_dotted_line_x_)) + sizeof(output_type_));
    num_months_ = 12;
    num_years_ = 30;
    first_month_ = 1;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool CalendarConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:config.CalendarConfig)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 num_years = 1 [default = 30];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_num_years();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &num_years_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 first_month = 2 [default = 1];
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_first_month();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &first_month_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 num_months = 3 [default = 12];
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          set_has_num_months();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &num_months_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .config.SpecialDay special_day = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_special_day()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double cell_size = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(41u /* 41 & 0xFF */)) {
          set_has_cell_size();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &cell_size_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double cell_margin = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(49u /* 49 & 0xFF */)) {
          set_has_cell_margin();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &cell_margin_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double font_size = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(57u /* 57 & 0xFF */)) {
          set_has_font_size();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &font_size_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double bigger_font_size = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(65u /* 65 & 0xFF */)) {
          set_has_bigger_font_size();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &bigger_font_size_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double line_width = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(73u /* 73 & 0xFF */)) {
          set_has_line_width();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &line_width_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double month_label_height = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(81u /* 81 & 0xFF */)) {
          set_has_month_label_height();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &month_label_height_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double year_label_width = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(89u /* 89 & 0xFF */)) {
          set_has_year_label_width();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &year_label_width_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .config.RGB rgb_header = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(98u /* 98 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_rgb_header()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .config.RGB rgb_header_sunday = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(106u /* 106 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_rgb_header_sunday()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .config.RGB rgb_month_line = 14;
      case 14: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(114u /* 114 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_rgb_month_line()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .config.RGB rgb_holiday = 15;
      case 15: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(122u /* 122 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_rgb_holiday()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string bottom_left_label = 16;
      case 16: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(130u /* 130 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_bottom_left_label()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->bottom_left_label().data(), static_cast<int>(this->bottom_left_label().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "config.CalendarConfig.bottom_left_label");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string bottom_right_label = 17;
      case 17: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(138u /* 138 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_bottom_right_label()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->bottom_right_label().data(), static_cast<int>(this->bottom_right_label().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "config.CalendarConfig.bottom_right_label");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string header_font_family = 18;
      case 18: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(146u /* 146 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_header_font_family()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->header_font_family().data(), static_cast<int>(this->header_font_family().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "config.CalendarConfig.header_font_family");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string number_font_family = 19;
      case 19: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(154u /* 154 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_number_font_family()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->number_font_family().data(), static_cast<int>(this->number_font_family().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "config.CalendarConfig.number_font_family");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string quote_font_family = 20;
      case 20: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(162u /* 162 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_quote_font_family()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->quote_font_family().data(), static_cast<int>(this->quote_font_family().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "config.CalendarConfig.quote_font_family");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bool dotted_line = 21 [default = false];
      case 21: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(168u /* 168 & 0xFF */)) {
          set_has_dotted_line();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &dotted_line_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double vertical_dotted_line_x = 22;
      case 22: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(177u /* 177 & 0xFF */)) {
          set_has_vertical_dotted_line_x();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &vertical_dotted_line_x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .config.OutputType output_type = 23 [default = SVG];
      case 23: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(184u /* 184 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::config::OutputType_IsValid(value)) {
            set_output_type(static_cast< ::config::OutputType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                23, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:config.CalendarConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:config.CalendarConfig)
  return false;
#undef DO_
}

void CalendarConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:config.CalendarConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 num_years = 1 [default = 30];
  if (cached_has_bits & 0x00100000u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->num_years(), output);
  }

  // optional int32 first_month = 2 [default = 1];
  if (cached_has_bits & 0x00200000u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->first_month(), output);
  }

  // optional int32 num_months = 3 [default = 12];
  if (cached_has_bits & 0x00080000u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->num_months(), output);
  }

  // repeated .config.SpecialDay special_day = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->special_day_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4,
      this->special_day(static_cast<int>(i)),
      output);
  }

  // optional double cell_size = 5;
  if (cached_has_bits & 0x00000200u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->cell_size(), output);
  }

  // optional double cell_margin = 6;
  if (cached_has_bits & 0x00000400u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(6, this->cell_margin(), output);
  }

  // optional double font_size = 7;
  if (cached_has_bits & 0x00000800u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(7, this->font_size(), output);
  }

  // optional double bigger_font_size = 8;
  if (cached_has_bits & 0x00001000u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(8, this->bigger_font_size(), output);
  }

  // optional double line_width = 9;
  if (cached_has_bits & 0x00002000u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(9, this->line_width(), output);
  }

  // optional double month_label_height = 10;
  if (cached_has_bits & 0x00004000u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(10, this->month_label_height(), output);
  }

  // optional double year_label_width = 11;
  if (cached_has_bits & 0x00008000u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(11, this->year_label_width(), output);
  }

  // optional .config.RGB rgb_header = 12;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      12, this->_internal_rgb_header(), output);
  }

  // optional .config.RGB rgb_header_sunday = 13;
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      13, this->_internal_rgb_header_sunday(), output);
  }

  // optional .config.RGB rgb_month_line = 14;
  if (cached_has_bits & 0x00000080u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      14, this->_internal_rgb_month_line(), output);
  }

  // optional .config.RGB rgb_holiday = 15;
  if (cached_has_bits & 0x00000100u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      15, this->_internal_rgb_holiday(), output);
  }

  // optional string bottom_left_label = 16;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->bottom_left_label().data(), static_cast<int>(this->bottom_left_label().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "config.CalendarConfig.bottom_left_label");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      16, this->bottom_left_label(), output);
  }

  // optional string bottom_right_label = 17;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->bottom_right_label().data(), static_cast<int>(this->bottom_right_label().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "config.CalendarConfig.bottom_right_label");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      17, this->bottom_right_label(), output);
  }

  // optional string header_font_family = 18;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->header_font_family().data(), static_cast<int>(this->header_font_family().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "config.CalendarConfig.header_font_family");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      18, this->header_font_family(), output);
  }

  // optional string number_font_family = 19;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->number_font_family().data(), static_cast<int>(this->number_font_family().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "config.CalendarConfig.number_font_family");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      19, this->number_font_family(), output);
  }

  // optional string quote_font_family = 20;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->quote_font_family().data(), static_cast<int>(this->quote_font_family().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "config.CalendarConfig.quote_font_family");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      20, this->quote_font_family(), output);
  }

  // optional bool dotted_line = 21 [default = false];
  if (cached_has_bits & 0x00020000u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(21, this->dotted_line(), output);
  }

  // optional double vertical_dotted_line_x = 22;
  if (cached_has_bits & 0x00010000u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(22, this->vertical_dotted_line_x(), output);
  }

  // optional .config.OutputType output_type = 23 [default = SVG];
  if (cached_has_bits & 0x00040000u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      23, this->output_type(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:config.CalendarConfig)
}

::google::protobuf::uint8* CalendarConfig::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:config.CalendarConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 num_years = 1 [default = 30];
  if (cached_has_bits & 0x00100000u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->num_years(), target);
  }

  // optional int32 first_month = 2 [default = 1];
  if (cached_has_bits & 0x00200000u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->first_month(), target);
  }

  // optional int32 num_months = 3 [default = 12];
  if (cached_has_bits & 0x00080000u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->num_months(), target);
  }

  // repeated .config.SpecialDay special_day = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->special_day_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->special_day(static_cast<int>(i)), deterministic, target);
  }

  // optional double cell_size = 5;
  if (cached_has_bits & 0x00000200u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->cell_size(), target);
  }

  // optional double cell_margin = 6;
  if (cached_has_bits & 0x00000400u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(6, this->cell_margin(), target);
  }

  // optional double font_size = 7;
  if (cached_has_bits & 0x00000800u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(7, this->font_size(), target);
  }

  // optional double bigger_font_size = 8;
  if (cached_has_bits & 0x00001000u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(8, this->bigger_font_size(), target);
  }

  // optional double line_width = 9;
  if (cached_has_bits & 0x00002000u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(9, this->line_width(), target);
  }

  // optional double month_label_height = 10;
  if (cached_has_bits & 0x00004000u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(10, this->month_label_height(), target);
  }

  // optional double year_label_width = 11;
  if (cached_has_bits & 0x00008000u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(11, this->year_label_width(), target);
  }

  // optional .config.RGB rgb_header = 12;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        12, this->_internal_rgb_header(), deterministic, target);
  }

  // optional .config.RGB rgb_header_sunday = 13;
  if (cached_has_bits & 0x00000040u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        13, this->_internal_rgb_header_sunday(), deterministic, target);
  }

  // optional .config.RGB rgb_month_line = 14;
  if (cached_has_bits & 0x00000080u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        14, this->_internal_rgb_month_line(), deterministic, target);
  }

  // optional .config.RGB rgb_holiday = 15;
  if (cached_has_bits & 0x00000100u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        15, this->_internal_rgb_holiday(), deterministic, target);
  }

  // optional string bottom_left_label = 16;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->bottom_left_label().data(), static_cast<int>(this->bottom_left_label().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "config.CalendarConfig.bottom_left_label");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        16, this->bottom_left_label(), target);
  }

  // optional string bottom_right_label = 17;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->bottom_right_label().data(), static_cast<int>(this->bottom_right_label().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "config.CalendarConfig.bottom_right_label");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        17, this->bottom_right_label(), target);
  }

  // optional string header_font_family = 18;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->header_font_family().data(), static_cast<int>(this->header_font_family().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "config.CalendarConfig.header_font_family");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        18, this->header_font_family(), target);
  }

  // optional string number_font_family = 19;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->number_font_family().data(), static_cast<int>(this->number_font_family().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "config.CalendarConfig.number_font_family");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        19, this->number_font_family(), target);
  }

  // optional string quote_font_family = 20;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->quote_font_family().data(), static_cast<int>(this->quote_font_family().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "config.CalendarConfig.quote_font_family");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        20, this->quote_font_family(), target);
  }

  // optional bool dotted_line = 21 [default = false];
  if (cached_has_bits & 0x00020000u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(21, this->dotted_line(), target);
  }

  // optional double vertical_dotted_line_x = 22;
  if (cached_has_bits & 0x00010000u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(22, this->vertical_dotted_line_x(), target);
  }

  // optional .config.OutputType output_type = 23 [default = SVG];
  if (cached_has_bits & 0x00040000u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      23, this->output_type(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:config.CalendarConfig)
  return target;
}

size_t CalendarConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:config.CalendarConfig)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated .config.SpecialDay special_day = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->special_day_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->special_day(static_cast<int>(i)));
    }
  }

  if (_has_bits_[0 / 32] & 255u) {
    // optional string bottom_left_label = 16;
    if (has_bottom_left_label()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->bottom_left_label());
    }

    // optional string bottom_right_label = 17;
    if (has_bottom_right_label()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->bottom_right_label());
    }

    // optional string header_font_family = 18;
    if (has_header_font_family()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->header_font_family());
    }

    // optional string number_font_family = 19;
    if (has_number_font_family()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->number_font_family());
    }

    // optional string quote_font_family = 20;
    if (has_quote_font_family()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->quote_font_family());
    }

    // optional .config.RGB rgb_header = 12;
    if (has_rgb_header()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *rgb_header_);
    }

    // optional .config.RGB rgb_header_sunday = 13;
    if (has_rgb_header_sunday()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *rgb_header_sunday_);
    }

    // optional .config.RGB rgb_month_line = 14;
    if (has_rgb_month_line()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *rgb_month_line_);
    }

  }
  if (_has_bits_[8 / 32] & 65280u) {
    // optional .config.RGB rgb_holiday = 15;
    if (has_rgb_holiday()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *rgb_holiday_);
    }

    // optional double cell_size = 5;
    if (has_cell_size()) {
      total_size += 1 + 8;
    }

    // optional double cell_margin = 6;
    if (has_cell_margin()) {
      total_size += 1 + 8;
    }

    // optional double font_size = 7;
    if (has_font_size()) {
      total_size += 1 + 8;
    }

    // optional double bigger_font_size = 8;
    if (has_bigger_font_size()) {
      total_size += 1 + 8;
    }

    // optional double line_width = 9;
    if (has_line_width()) {
      total_size += 1 + 8;
    }

    // optional double month_label_height = 10;
    if (has_month_label_height()) {
      total_size += 1 + 8;
    }

    // optional double year_label_width = 11;
    if (has_year_label_width()) {
      total_size += 1 + 8;
    }

  }
  if (_has_bits_[16 / 32] & 4128768u) {
    // optional double vertical_dotted_line_x = 22;
    if (has_vertical_dotted_line_x()) {
      total_size += 2 + 8;
    }

    // optional bool dotted_line = 21 [default = false];
    if (has_dotted_line()) {
      total_size += 2 + 1;
    }

    // optional .config.OutputType output_type = 23 [default = SVG];
    if (has_output_type()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->output_type());
    }

    // optional int32 num_months = 3 [default = 12];
    if (has_num_months()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->num_months());
    }

    // optional int32 num_years = 1 [default = 30];
    if (has_num_years()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->num_years());
    }

    // optional int32 first_month = 2 [default = 1];
    if (has_first_month()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->first_month());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CalendarConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:config.CalendarConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const CalendarConfig* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CalendarConfig>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:config.CalendarConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:config.CalendarConfig)
    MergeFrom(*source);
  }
}

void CalendarConfig::MergeFrom(const CalendarConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:config.CalendarConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  special_day_.MergeFrom(from.special_day_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 255u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_bottom_left_label();
      bottom_left_label_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bottom_left_label_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_bottom_right_label();
      bottom_right_label_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bottom_right_label_);
    }
    if (cached_has_bits & 0x00000004u) {
      set_has_header_font_family();
      header_font_family_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.header_font_family_);
    }
    if (cached_has_bits & 0x00000008u) {
      set_has_number_font_family();
      number_font_family_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.number_font_family_);
    }
    if (cached_has_bits & 0x00000010u) {
      set_has_quote_font_family();
      quote_font_family_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.quote_font_family_);
    }
    if (cached_has_bits & 0x00000020u) {
      mutable_rgb_header()->::config::RGB::MergeFrom(from.rgb_header());
    }
    if (cached_has_bits & 0x00000040u) {
      mutable_rgb_header_sunday()->::config::RGB::MergeFrom(from.rgb_header_sunday());
    }
    if (cached_has_bits & 0x00000080u) {
      mutable_rgb_month_line()->::config::RGB::MergeFrom(from.rgb_month_line());
    }
  }
  if (cached_has_bits & 65280u) {
    if (cached_has_bits & 0x00000100u) {
      mutable_rgb_holiday()->::config::RGB::MergeFrom(from.rgb_holiday());
    }
    if (cached_has_bits & 0x00000200u) {
      cell_size_ = from.cell_size_;
    }
    if (cached_has_bits & 0x00000400u) {
      cell_margin_ = from.cell_margin_;
    }
    if (cached_has_bits & 0x00000800u) {
      font_size_ = from.font_size_;
    }
    if (cached_has_bits & 0x00001000u) {
      bigger_font_size_ = from.bigger_font_size_;
    }
    if (cached_has_bits & 0x00002000u) {
      line_width_ = from.line_width_;
    }
    if (cached_has_bits & 0x00004000u) {
      month_label_height_ = from.month_label_height_;
    }
    if (cached_has_bits & 0x00008000u) {
      year_label_width_ = from.year_label_width_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 4128768u) {
    if (cached_has_bits & 0x00010000u) {
      vertical_dotted_line_x_ = from.vertical_dotted_line_x_;
    }
    if (cached_has_bits & 0x00020000u) {
      dotted_line_ = from.dotted_line_;
    }
    if (cached_has_bits & 0x00040000u) {
      output_type_ = from.output_type_;
    }
    if (cached_has_bits & 0x00080000u) {
      num_months_ = from.num_months_;
    }
    if (cached_has_bits & 0x00100000u) {
      num_years_ = from.num_years_;
    }
    if (cached_has_bits & 0x00200000u) {
      first_month_ = from.first_month_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void CalendarConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:config.CalendarConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CalendarConfig::CopyFrom(const CalendarConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:config.CalendarConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CalendarConfig::IsInitialized() const {
  if (!::google::protobuf::internal::AllAreInitialized(this->special_day())) return false;
  if (has_rgb_header()) {
    if (!this->rgb_header_->IsInitialized()) return false;
  }
  if (has_rgb_header_sunday()) {
    if (!this->rgb_header_sunday_->IsInitialized()) return false;
  }
  if (has_rgb_month_line()) {
    if (!this->rgb_month_line_->IsInitialized()) return false;
  }
  if (has_rgb_holiday()) {
    if (!this->rgb_holiday_->IsInitialized()) return false;
  }
  return true;
}

void CalendarConfig::Swap(CalendarConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CalendarConfig::InternalSwap(CalendarConfig* other) {
  using std::swap;
  CastToBase(&special_day_)->InternalSwap(CastToBase(&other->special_day_));
  bottom_left_label_.Swap(&other->bottom_left_label_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  bottom_right_label_.Swap(&other->bottom_right_label_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  header_font_family_.Swap(&other->header_font_family_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  number_font_family_.Swap(&other->number_font_family_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  quote_font_family_.Swap(&other->quote_font_family_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(rgb_header_, other->rgb_header_);
  swap(rgb_header_sunday_, other->rgb_header_sunday_);
  swap(rgb_month_line_, other->rgb_month_line_);
  swap(rgb_holiday_, other->rgb_holiday_);
  swap(cell_size_, other->cell_size_);
  swap(cell_margin_, other->cell_margin_);
  swap(font_size_, other->font_size_);
  swap(bigger_font_size_, other->bigger_font_size_);
  swap(line_width_, other->line_width_);
  swap(month_label_height_, other->month_label_height_);
  swap(year_label_width_, other->year_label_width_);
  swap(vertical_dotted_line_x_, other->vertical_dotted_line_x_);
  swap(dotted_line_, other->dotted_line_);
  swap(output_type_, other->output_type_);
  swap(num_months_, other->num_months_);
  swap(num_years_, other->num_years_);
  swap(first_month_, other->first_month_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CalendarConfig::GetMetadata() const {
  protobuf_config_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_config_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SpecialDay::InitAsDefaultInstance() {
  ::config::_SpecialDay_default_instance_._instance.get_mutable()->rgb_ = const_cast< ::config::RGB*>(
      ::config::RGB::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SpecialDay::kMonthFieldNumber;
const int SpecialDay::kDayFieldNumber;
const int SpecialDay::kSvgFieldNumber;
const int SpecialDay::kFirstYearFieldNumber;
const int SpecialDay::kYearFieldNumber;
const int SpecialDay::kRgbFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SpecialDay::SpecialDay()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_config_2eproto::scc_info_SpecialDay.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:config.SpecialDay)
}
SpecialDay::SpecialDay(const SpecialDay& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  svg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_svg()) {
    svg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.svg_);
  }
  if (from.has_rgb()) {
    rgb_ = new ::config::RGB(*from.rgb_);
  } else {
    rgb_ = NULL;
  }
  ::memcpy(&month_, &from.month_,
    static_cast<size_t>(reinterpret_cast<char*>(&year_) -
    reinterpret_cast<char*>(&month_)) + sizeof(year_));
  // @@protoc_insertion_point(copy_constructor:config.SpecialDay)
}

void SpecialDay::SharedCtor() {
  svg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&rgb_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&year_) -
      reinterpret_cast<char*>(&rgb_)) + sizeof(year_));
}

SpecialDay::~SpecialDay() {
  // @@protoc_insertion_point(destructor:config.SpecialDay)
  SharedDtor();
}

void SpecialDay::SharedDtor() {
  svg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete rgb_;
}

void SpecialDay::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SpecialDay::descriptor() {
  ::protobuf_config_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_config_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SpecialDay& SpecialDay::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_config_2eproto::scc_info_SpecialDay.base);
  return *internal_default_instance();
}


void SpecialDay::Clear() {
// @@protoc_insertion_point(message_clear_start:config.SpecialDay)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      svg_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(rgb_ != NULL);
      rgb_->Clear();
    }
  }
  if (cached_has_bits & 60u) {
    ::memset(&month_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&year_) -
        reinterpret_cast<char*>(&month_)) + sizeof(year_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool SpecialDay::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:config.SpecialDay)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 month = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_month();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &month_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 day = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_day();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &day_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string svg = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_svg()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->svg().data(), static_cast<int>(this->svg().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "config.SpecialDay.svg");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 first_year = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          set_has_first_year();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &first_year_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 year = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {
          set_has_year();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &year_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .config.RGB rgb = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_rgb()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:config.SpecialDay)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:config.SpecialDay)
  return false;
#undef DO_
}

void SpecialDay::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:config.SpecialDay)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 month = 1;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->month(), output);
  }

  // required int32 day = 2;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->day(), output);
  }

  // optional string svg = 3;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->svg().data(), static_cast<int>(this->svg().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "config.SpecialDay.svg");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->svg(), output);
  }

  // optional int32 first_year = 4;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->first_year(), output);
  }

  // optional int32 year = 5;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->year(), output);
  }

  // optional .config.RGB rgb = 6;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->_internal_rgb(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:config.SpecialDay)
}

::google::protobuf::uint8* SpecialDay::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:config.SpecialDay)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 month = 1;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->month(), target);
  }

  // required int32 day = 2;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->day(), target);
  }

  // optional string svg = 3;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->svg().data(), static_cast<int>(this->svg().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "config.SpecialDay.svg");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->svg(), target);
  }

  // optional int32 first_year = 4;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->first_year(), target);
  }

  // optional int32 year = 5;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->year(), target);
  }

  // optional .config.RGB rgb = 6;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, this->_internal_rgb(), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:config.SpecialDay)
  return target;
}

size_t SpecialDay::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:config.SpecialDay)
  size_t total_size = 0;

  if (has_month()) {
    // required int32 month = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->month());
  }

  if (has_day()) {
    // required int32 day = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->day());
  }

  return total_size;
}
size_t SpecialDay::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:config.SpecialDay)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x0000000c) ^ 0x0000000c) == 0) {  // All required fields are present.
    // required int32 month = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->month());

    // required int32 day = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->day());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_has_bits_[0 / 32] & 3u) {
    // optional string svg = 3;
    if (has_svg()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->svg());
    }

    // optional .config.RGB rgb = 6;
    if (has_rgb()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *rgb_);
    }

  }
  if (_has_bits_[0 / 32] & 48u) {
    // optional int32 first_year = 4;
    if (has_first_year()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->first_year());
    }

    // optional int32 year = 5;
    if (has_year()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->year());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SpecialDay::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:config.SpecialDay)
  GOOGLE_DCHECK_NE(&from, this);
  const SpecialDay* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SpecialDay>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:config.SpecialDay)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:config.SpecialDay)
    MergeFrom(*source);
  }
}

void SpecialDay::MergeFrom(const SpecialDay& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:config.SpecialDay)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 63u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_svg();
      svg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.svg_);
    }
    if (cached_has_bits & 0x00000002u) {
      mutable_rgb()->::config::RGB::MergeFrom(from.rgb());
    }
    if (cached_has_bits & 0x00000004u) {
      month_ = from.month_;
    }
    if (cached_has_bits & 0x00000008u) {
      day_ = from.day_;
    }
    if (cached_has_bits & 0x00000010u) {
      first_year_ = from.first_year_;
    }
    if (cached_has_bits & 0x00000020u) {
      year_ = from.year_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void SpecialDay::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:config.SpecialDay)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SpecialDay::CopyFrom(const SpecialDay& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:config.SpecialDay)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpecialDay::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000c) != 0x0000000c) return false;
  if (has_rgb()) {
    if (!this->rgb_->IsInitialized()) return false;
  }
  return true;
}

void SpecialDay::Swap(SpecialDay* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SpecialDay::InternalSwap(SpecialDay* other) {
  using std::swap;
  svg_.Swap(&other->svg_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(rgb_, other->rgb_);
  swap(month_, other->month_);
  swap(day_, other->day_);
  swap(first_year_, other->first_year_);
  swap(year_, other->year_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SpecialDay::GetMetadata() const {
  protobuf_config_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_config_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void RGB::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RGB::kRedFieldNumber;
const int RGB::kGreenFieldNumber;
const int RGB::kBlueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RGB::RGB()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_config_2eproto::scc_info_RGB.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:config.RGB)
}
RGB::RGB(const RGB& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&red_, &from.red_,
    static_cast<size_t>(reinterpret_cast<char*>(&blue_) -
    reinterpret_cast<char*>(&red_)) + sizeof(blue_));
  // @@protoc_insertion_point(copy_constructor:config.RGB)
}

void RGB::SharedCtor() {
  ::memset(&red_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&blue_) -
      reinterpret_cast<char*>(&red_)) + sizeof(blue_));
}

RGB::~RGB() {
  // @@protoc_insertion_point(destructor:config.RGB)
  SharedDtor();
}

void RGB::SharedDtor() {
}

void RGB::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* RGB::descriptor() {
  ::protobuf_config_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_config_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const RGB& RGB::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_config_2eproto::scc_info_RGB.base);
  return *internal_default_instance();
}


void RGB::Clear() {
// @@protoc_insertion_point(message_clear_start:config.RGB)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 7u) {
    ::memset(&red_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&blue_) -
        reinterpret_cast<char*>(&red_)) + sizeof(blue_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool RGB::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:config.RGB)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 red = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_red();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &red_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 green = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_green();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &green_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 blue = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          set_has_blue();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &blue_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:config.RGB)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:config.RGB)
  return false;
#undef DO_
}

void RGB::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:config.RGB)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 red = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->red(), output);
  }

  // required int32 green = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->green(), output);
  }

  // required int32 blue = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->blue(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:config.RGB)
}

::google::protobuf::uint8* RGB::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:config.RGB)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 red = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->red(), target);
  }

  // required int32 green = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->green(), target);
  }

  // required int32 blue = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->blue(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:config.RGB)
  return target;
}

size_t RGB::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:config.RGB)
  size_t total_size = 0;

  if (has_red()) {
    // required int32 red = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->red());
  }

  if (has_green()) {
    // required int32 green = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->green());
  }

  if (has_blue()) {
    // required int32 blue = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->blue());
  }

  return total_size;
}
size_t RGB::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:config.RGB)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required int32 red = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->red());

    // required int32 green = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->green());

    // required int32 blue = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->blue());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RGB::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:config.RGB)
  GOOGLE_DCHECK_NE(&from, this);
  const RGB* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const RGB>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:config.RGB)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:config.RGB)
    MergeFrom(*source);
  }
}

void RGB::MergeFrom(const RGB& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:config.RGB)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      red_ = from.red_;
    }
    if (cached_has_bits & 0x00000002u) {
      green_ = from.green_;
    }
    if (cached_has_bits & 0x00000004u) {
      blue_ = from.blue_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void RGB::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:config.RGB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RGB::CopyFrom(const RGB& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:config.RGB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RGB::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;
  return true;
}

void RGB::Swap(RGB* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RGB::InternalSwap(RGB* other) {
  using std::swap;
  swap(red_, other->red_);
  swap(green_, other->green_);
  swap(blue_, other->blue_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata RGB::GetMetadata() const {
  protobuf_config_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_config_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace config
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::config::CalendarConfig* Arena::CreateMaybeMessage< ::config::CalendarConfig >(Arena* arena) {
  return Arena::CreateInternal< ::config::CalendarConfig >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::config::SpecialDay* Arena::CreateMaybeMessage< ::config::SpecialDay >(Arena* arena) {
  return Arena::CreateInternal< ::config::SpecialDay >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::config::RGB* Arena::CreateMaybeMessage< ::config::RGB >(Arena* arena) {
  return Arena::CreateInternal< ::config::RGB >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
